CREATE TABLE IF NOT EXISTS menu_item_categories (
    category_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_description    VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS menu_items (
    id BIGINT   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name        VARCHAR(255) NOT NULL UNIQUE,
    description VARCHAR(255) NOT NULL UNIQUE,
    price       DECIMAL(10, 2) NOT NULL,
    category_id BIGINT NOT NULL,

    CONSTRAINT fk_menu_item_category
        FOREIGN KEY (category_id)
        REFERENCES menu_item_categories(category_id)
        ON DELETE RESTRICT
);